import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
// @ts-ignore
import "./globals.css";
import { Toaster } from "sonner";
import { AppSidebar } from "@/components/ui/app-sidebar";
// @ts-ignore
import "leaflet/dist/leaflet.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased p-3`}
      >
        <SidebarProvider>
          <AppSidebar />
          <main className="w-full flex gap-3">
            <SidebarTrigger />
            {children}
            <Toaster richColors={true} position="top-right" />
          </main>
        </SidebarProvider>
      </body>
    </html>
  );
}
